<?php

namespace DW\CoreBundle\Repository;

/**
 * GangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GangRepository extends \Doctrine\ORM\EntityRepository
{
}
