<?php

namespace DW\CoreBundle\Repository;

/**
 * TunnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TunnelRepository extends \Doctrine\ORM\EntityRepository
{
}
